name: Node.js CI

on:
  push:
    branches: [main, dev, staging, production]
  pull_request:
    branches: [main, dev, staging, production]

concurrency:
  group: bangle-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SENTRY_NO_PROGRESS_BAR: 1
  GITHUB_OWNER: ${{ secrets.GH_OWNER }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
          corepack prepare --activate
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Lint
        run: pnpm run lint:ci
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
          corepack prepare --activate
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: test
        run: pnpm run test:ci
  e2e-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.48.2-focal
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
          corepack prepare --activate
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers
          restore-keys: |
            ${{ runner.os }}-playwright-browsers
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm -w run e2e-install
      - name: Run Playwright tests
        run: pnpm -w run e2e:ci
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      